title: Zetao Zhuang
email: izzetao@gmail.com
avatar: '/assets/avatar.png'
description: >
  Frontend Developer, Designer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zzetao.github.io"
github_username:  zzetao

# Build settings
markdown: kramdown


permalink: /:year/:month/:day/:title.html

gems: [jekyll-paginate]
paginate: 6
paginate_path: "/page/:num"
