name: Publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Environment
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - uses: actions/checkout@v2

    - name: Build
      run: |
        yarn
        yarn build

    - name: Checkout Branch
      run: |
        git reset --hard
        git fetch origin gh-pages
        git checkout gh-pages

    - name: Move assets
      run: |
        rm -rf assets/ index.html
        mv dist/index.html .
        mv dist/assets .

    - name: Git
      run: |
        git config --global user.email "i.zzetao@gmail.com"
        git config --global user.name "Bot"

    - name: Publish
      run: |
        git status
        git add index.html assets/*
        git commit -m "Publish page"
        git push --set-upstream origin gh-pages
